version: "3"

services:
  frontend:

    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    image: node-express
    volumes:
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    networks:
      - webnet
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - webnet
    volumes:
      - mongodata:/data/db

networks:
  webnet:
volumes:
  mongodata:
  node_modules: